[functions]

  [functions.refresh-bandi]
  schedule = "0 3 * * *"

[build]
command = "npm run build"
publish = ".next"

  [build.environment]
  NODE_VERSION = "20"

[[headers]]
for = "/_next/static/*"

  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/_next/image"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[[redirects]]
from = "/_ipx/*"
to = "/.netlify/images?url=:url&w=:width&q=:quality"
status = 200

  [redirects.query]
  url = ":url"
  w = ":width"
  q = ":quality"

[context]

  [context.deploy-preview]

    [[context.deploy-preview.headers]]
    for = "/_next/static/*"

      [context.deploy-preview.headers.values]
      Cache-Control = "public, max-age=31536000, immutable"

  [context."fix/netlify-preview-redirects"]

    [[context."fix/netlify-preview-redirects".headers]]
    for = "/_next/static/*"

      [context."fix/netlify-preview-redirects".headers.values]
      Cache-Control = "public, max-age=31536000, immutable"