export const STRATEGIC_SCANNER_DOCS = [
  {
    id: 'strategic-autoimpiego-centro-nord',
    title: 'Autoimpiego Centro-Nord',
    description:
      "Incentivo Invitalia per giovani under 35 inattivi, inoccupati, disoccupati, disoccupati GOL e working poor che vogliono avviare una nuova attività nel Centro-Nord. Sostiene nuove iniziative d'impresa, lavoro autonomo e libera professione con voucher e contributi a fondo perduto.",
    authorityName: 'Invitalia',
    openDate: null,
    closeDate: null,
    regions: [
      'Piemonte',
      "Valle d'Aosta",
      'Liguria',
      'Lombardia',
      'Veneto',
      'Friuli-Venezia Giulia',
      'Trentino-Alto Adige',
      'Emilia-Romagna',
      'Toscana',
      'Lazio',
      'Umbria',
      'Marche',
    ],
    sectors: ['Turismo', 'Commercio', 'Servizi', 'ICT', 'Digitale', 'Artigianato', 'Cultura', 'Ristorazione', 'Manifattura'],
    beneficiaries: [
      'Startup',
      'Aspiranti imprenditori',
      'Libero professionista',
      'Lavoro autonomo',
      'Under 35',
      'Disoccupati',
      'Inoccupati',
      'Working poor',
    ],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Start up/Sviluppo d impresa', 'Imprenditoria giovanile', 'Autoimpiego', 'Sostegno investimenti'],
    supportForm: ['Contributo/Fondo perduto', 'Voucher'],
    ateco: 'Tutti i settori economici ammissibili tranne agricoltura, pesca e acquacoltura',
    costMax: 200000,
    displayAmountLabel: 'Voucher fino a € 30.000 - € 40.000',
    displayProjectAmountLabel: 'Fino a € 200.000',
    displayCoverageLabel: '60% - 100%',
    coverageMinPercent: 60,
    coverageMaxPercent: 100,
    institutionalLink: 'https://www.invitalia.it/incentivi-e-strumenti/autoimpiego-centro-nord',
    url: '/incentivi-e-strumenti/autoimpiego-centro-nord',
    score: 99,
  },
  {
    id: 'strategic-resto-al-sud-20',
    title: 'Resto al Sud 2.0',
    description:
      "Incentivo Invitalia per under 35, disoccupati/inoccupati, working poor e nuove iniziative imprenditoriali o libero-professionali nel Mezzogiorno. Ammette turismo, commercio, servizi, digitale, artigianato, cultura, manifattura e ristorazione. Prevede voucher e contributi a fondo perduto per avvio di impresa e lavoro autonomo.",
    authorityName: 'Invitalia',
    openDate: null,
    closeDate: null,
    regions: ['Abruzzo', 'Basilicata', 'Calabria', 'Campania', 'Molise', 'Puglia', 'Sardegna', 'Sicilia'],
    sectors: ['Turismo', 'Commercio', 'Servizi', 'ICT', 'Digitale', 'Artigianato', 'Cultura', 'Ristorazione', 'Manifattura'],
    beneficiaries: ['Startup', 'Impresa', 'Aspiranti imprenditori', 'Libero professionista', 'Lavoro autonomo'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Start up/Sviluppo d impresa', 'Imprenditoria giovanile', 'Autoimpiego', 'Sostegno investimenti'],
    supportForm: ['Contributo/Fondo perduto', 'Voucher'],
    ateco: 'Tutti i settori economici ammissibili tranne agricoltura, pesca e acquacoltura',
    costMin: 10000,
    costMax: 200000,
    displayAmountLabel: 'Voucher fino a € 50.000 + contributo fino a € 150.000',
    displayProjectAmountLabel: 'Da € 10.000 a € 200.000',
    displayCoverageLabel: '70% - 100%',
    coverageMinPercent: 70,
    coverageMaxPercent: 100,
    institutionalLink: 'https://www.invitalia.it/incentivi-e-strumenti/resto-al-sud-20',
    url: '/incentivi-e-strumenti/resto-al-sud-20',
    score: 100,
  },
  {
    id: '81',
    title: 'Smart&Start Italia - Sostegno alle startup innovative',
    description:
      "Incentivo Invitalia per startup innovative e nuove imprese ad alto contenuto tecnologico. Sostiene progetti di innovazione, digitale, software, ricerca, sviluppo prodotto e crescita d impresa, con condizioni rafforzate nel Centro-Sud.",
    authorityName: 'Invitalia',
    openDate: null,
    closeDate: null,
    regions: ['Italia'],
    sectors: ['ICT', 'Digitale', 'Innovazione', 'Ricerca', 'Servizi', 'Manifattura'],
    beneficiaries: ['Startup innovativa', 'Impresa', 'Nuova impresa'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Innovazione e ricerca', 'Start up/Sviluppo d impresa', 'Digitalizzazione'],
    supportForm: ['Finanziamento agevolato', 'Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici delle startup innovative',
    costMin: 100000,
    costMax: 1500000,
    displayProjectAmountLabel: 'Da € 100.000 a € 1.500.000',
    displayCoverageLabel: '0%',
    coverageMinPercent: 0,
    coverageMaxPercent: 0,
    url: '/it/catalogo/smartstart-italia-sostegno-alle-startup-innovative',
    score: 95,
  },
  {
    id: 'strategic-fusese',
    title: 'FUSESE - Fund for self employment and self entrepreneurship',
    description:
      "Programma europeo gestito in Italia dalla Regione Calabria e altri enti per favorire l'autoimpiego e l'avvio di nuove attivita imprenditoriali, con contributi a fondo perduto e servizi di accompagnamento per giovani, disoccupati e inoccupati nel Mezzogiorno.",
    authorityName: 'Regione Calabria',
    openDate: null,
    closeDate: null,
    regions: ['Calabria', 'Campania', 'Puglia', 'Sicilia', 'Basilicata', 'Sardegna', 'Molise', 'Abruzzo'],
    sectors: ['Turismo', 'Commercio', 'Servizi', 'ICT', 'Digitale', 'Artigianato', 'Cultura', 'Ristorazione', 'Manifattura'],
    beneficiaries: ['Startup', 'Aspiranti imprenditori', 'Disoccupati', 'Inoccupati', 'Under 35', 'Lavoro autonomo'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Start up/Sviluppo d impresa', 'Autoimpiego', 'Imprenditoria giovanile'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici ammissibili',
    costMin: 5000,
    costMax: 50000,
    displayProjectAmountLabel: 'Fino a € 50.000',
    displayCoverageLabel: '65% - 80%',
    coverageMinPercent: 65,
    coverageMaxPercent: 80,
    url: '/fusese',
    score: 94,
  },
  {
    id: '83',
    title: 'ON - Oltre Nuove imprese a tasso zero',
    description:
      "Misura Invitalia per nuove micro e piccole imprese giovanili o femminili. Favorisce avvio di impresa, investimento produttivo, turismo, servizi, commercio e manifattura con mix di finanziamento agevolato e contributo a fondo perduto.",
    authorityName: "Invitalia - Agenzia nazionale per l'attrazione degli investimenti e lo sviluppo d'impresa S.p.A.",
    openDate: null,
    closeDate: null,
    regions: ['Italia'],
    sectors: ['Turismo', 'Commercio', 'Servizi', 'Manifattura', 'Artigianato', 'Cultura'],
    beneficiaries: ['Nuova impresa', 'Impresa giovanile', 'Impresa femminile', 'Startup'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Start up/Sviluppo d impresa', 'Imprenditoria giovanile', 'Imprenditoria femminile', 'Sostegno investimenti'],
    supportForm: ['Finanziamento agevolato', 'Contributo/Fondo perduto'],
    ateco: 'Settori produttivi, turismo, commercio e servizi',
    costMin: 50000,
    costMax: 3000000,
    displayProjectAmountLabel: 'Fino a € 3.000.000',
    displayCoverageLabel: '20%',
    coverageMinPercent: 20,
    coverageMaxPercent: 20,
    grantMax: 600000,
    url: '/it/catalogo/oltre-nuove-imprese-tasso-zero',
    score: 92,
  },
  {
    id: 'strategic-fondo-impresa-femminile',
    title: 'Fondo impresa femminile',
    description:
      "Agevolazione Invitalia per avvio e consolidamento di imprese femminili, con contributi e finanziamenti per investimento, servizi, commercio, turismo, manifattura e innovazione.",
    authorityName: 'Invitalia',
    openDate: null,
    closeDate: null,
    regions: ['Italia'],
    sectors: ['Turismo', 'Commercio', 'Servizi', 'Manifattura', 'Artigianato', 'Innovazione'],
    beneficiaries: ['Impresa femminile', 'Nuova impresa', 'Impresa'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Imprenditoria femminile', 'Start up/Sviluppo d impresa', 'Sostegno investimenti'],
    supportForm: ['Contributo/Fondo perduto', 'Finanziamento agevolato'],
    ateco: 'Settori economici ammissibili per imprese femminili',
    costMin: 30000,
    costMax: 400000,
    displayProjectAmountLabel: 'Da € 30.000 a € 400.000',
    displayCoverageLabel: '0%',
    coverageMinPercent: 0,
    coverageMaxPercent: 0,
    institutionalLink: 'https://www.invitalia.it/cosa-facciamo/creiamo-nuove-aziende/fondo-impresa-femminile',
    url: '/cosa-facciamo/creiamo-nuove-aziende/fondo-impresa-femminile',
    score: 88,
  },
  {
    id: '52',
    title: 'Beni Strumentali - Nuova Sabatini',
    description:
      "Misura nazionale per PMI gia attive che investono in macchinari, beni strumentali, digitale, software, hardware, tecnologie 4.0 e transizione digitale.",
    authorityName: 'Ministero delle Imprese e del Made in Italy',
    openDate: null,
    closeDate: null,
    regions: ['Italia'],
    sectors: ['Manifattura', 'Digitale', 'ICT', 'Commercio', 'Servizi'],
    beneficiaries: ['PMI', 'Impresa', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Digitalizzazione', 'Sostegno investimenti', 'Industria 4 0'],
    supportForm: ['Finanziamento agevolato', 'Contributo'],
    ateco: 'PMI ammissibili nei settori economici previsti dalla misura',
    costMin: 20000,
    costMax: 4000000,
    grantMin: 550,
    grantMax: 143000,
    displayAmountLabel: 'Contributo calcolato su finanziamenti da € 20.000 a € 4.000.000',
    displayProjectAmountLabel: 'Da € 20.000 a € 4.000.000',
    displayCoverageLabel: '0%',
    coverageMinPercent: 0,
    coverageMaxPercent: 0,
    url: '/it/incentivi/nuova-sabatini',
    score: 86,
  },
  {
    id: '2689',
    title: 'Polo di Innovazione Digitale PIDNEXT - servizi di first e post assessment',
    description:
      "Misura del sistema camerale per micro, piccole e medie imprese gia attive e iscritte al registro delle imprese che vogliono valutare la maturita digitale e ricevere servizi di first assessment e orientamento verso la trasformazione digitale.",
    authorityName: 'Ministero delle Imprese e del Made in Italy',
    openDate: '2023-03-10T00:00:00',
    closeDate: '2026-04-30T00:00:00',
    regions: [
      'Piemonte',
      'Lombardia',
      "Valle d'Aosta",
      'Liguria',
      'Abruzzo',
      'Molise',
      'Basilicata',
      'Calabria',
      'Campania',
      'Puglia',
      'Sicilia',
      'Trentino-Alto Adige',
      'Veneto',
      'Sardegna',
      'Toscana',
      'Friuli-Venezia Giulia',
      'Emilia-Romagna',
      'Umbria',
      'Marche',
      'Lazio',
    ],
    sectors: [
      'Agroalimentare',
      'Alberghiero',
      'Altri servizi',
      'Artigianato',
      'Commercio',
      'Cultura',
      'Edilizia',
      'ICT',
      'Manifattura',
      'Ristorazione',
      'Turismo',
    ],
    beneficiaries: ['Impresa', 'PMI', 'Azienda gia attiva', 'Impresa iscritta al registro imprese'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Digitalizzazione', 'Innovazione e ricerca', 'Start up/Sviluppo d impresa'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici ammissibili a ricevere aiuti',
    costMax: 2883,
    grantMax: 2883,
    displayProjectAmountLabel: 'Fino a € 2.883',
    displayCoverageLabel: '100%',
    coverageMinPercent: 100,
    coverageMaxPercent: 100,
    url: '/it/catalogo/polo-di-innovazione-digitale-pidnext-servizi-di-first-e-post-assessment',
    score: 90,
  },
  {
    id: '3800',
    title: 'PR Marche FESR 2021/2027 – Intervento 1.3.4.1 - Partecipazione delle imprese alla fiera SMAU Milano 2026',
    description:
      "Bando Regione Marche per startup e PMI innovative marchigiane gia costituite che partecipano a SMAU Milano 2026 con spazi espositivi e attivita di promozione per l'internazionalizzazione.",
    authorityName: 'Regione Marche',
    openDate: '2026-02-20T00:00:00',
    closeDate: '2026-04-16T00:00:00',
    regions: ['Marche'],
    sectors: ['Altri servizi', 'ICT', 'Digitale', 'Innovazione'],
    beneficiaries: ['Startup innovativa', 'PMI innovativa', 'Impresa', 'Impresa gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Internazionalizzazione', 'Innovazione e ricerca'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici ammissibili a ricevere aiuti',
    costMax: 5000,
    grantMax: 5000,
    displayProjectAmountLabel: 'Fino a € 5.000',
    displayCoverageLabel: '100%',
    coverageMinPercent: 100,
    coverageMaxPercent: 100,
    url: '/it/catalogo/pr-marche-fesr-20212027-intervento-1341-partecipazione-delle-imprese-alla-fiera-smau',
    score: 89,
  },
  {
    id: '7755',
    title: 'CCIAA Cosenza - Bando Voucher digitali I4.0 Anno 2026 XII Edizione – PID avanzato',
    description:
      "Bando della Camera di Commercio di Cosenza per micro, piccole e medie imprese gia attive della provincia che investono in digitalizzazione, ecommerce, CRM, cybersecurity, software e tecnologie 4.0.",
    authorityName: 'Camera di Commercio, Industria, Artigianato e Agricoltura di Cosenza',
    openDate: '2026-03-04T00:00:00',
    closeDate: '2026-09-30T00:00:00',
    regions: ['Calabria'],
    sectors: [
      'Altri servizi',
      'Artigianato',
      'Commercio',
      'ICT',
      'Manifattura',
      'Turismo',
      'Ristorazione',
      'Agroalimentare',
    ],
    beneficiaries: ['Impresa', 'PMI', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Digitalizzazione', 'Innovazione e ricerca'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici ammissibili a ricevere aiuti',
    costMin: 4000,
    costMax: 20000,
    grantMin: 2000,
    grantMax: 10000,
    displayAmountLabel: 'Da € 2.000 a € 10.000',
    displayProjectAmountLabel: 'Da € 4.000 a € 20.000',
    displayCoverageLabel: '50% - 70%',
    coverageMinPercent: 50,
    coverageMaxPercent: 70,
    url: '/it/catalogo/cciaa-cosenza-bando-voucher-digitali-i40-anno-2026-xii-edizione-pid-avanzato',
    score: 90,
  },
  {
    id: '7786',
    title: 'CCIAA Bologna - Contributi per la partecipazione a fiere internazionali in Italia - Anno 2026',
    description:
      "Bando della Camera di Commercio di Bologna per micro, piccole e medie imprese gia attive della citta metropolitana che partecipano a fiere internazionali certificate in Italia.",
    authorityName: 'Camera di Commercio, Industria, Artigianato e Agricoltura di Bologna',
    openDate: '2026-01-01T00:00:00',
    closeDate: '2026-12-31T00:00:00',
    regions: ['Emilia-Romagna'],
    sectors: ['Commercio', 'Manifattura', 'Servizi', 'Turismo', 'Artigianato', 'ICT'],
    beneficiaries: ['Impresa', 'PMI', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Internazionalizzazione'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici ammissibili a ricevere aiuti',
    costMin: 3000,
    costMax: 8000,
    grantMin: 1500,
    grantMax: 4000,
    displayAmountLabel: 'Da € 1.500 a € 4.000',
    displayProjectAmountLabel: 'Da € 3.000 a € 8.000',
    displayCoverageLabel: '50%',
    coverageMinPercent: 50,
    coverageMaxPercent: 50,
    url: '/it/catalogo/cciaa-bologna-contributi-la-partecipazione-fiere-internazionali-italia-anno-2026',
    score: 88,
  },
  {
    id: '7875',
    title: 'Regione Veneto - Bando per il consolidamento delle startup innovative',
    description:
      'Bando Regione Veneto per startup innovative gia costituite che vogliono consolidarsi con progetti di ricerca, innovazione, assunzione di personale qualificato e collaborazione con organismi di ricerca.',
    authorityName: 'Agenzia veneta per i pagamenti in agricoltura - AVEPA',
    openDate: '2026-02-10T00:00:00',
    closeDate: null,
    regions: ['Veneto'],
    sectors: ['ICT', 'Digitale', 'Innovazione', 'Servizi', 'Manifattura', 'Ricerca'],
    beneficiaries: ['Startup innovativa', 'Impresa', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Innovazione e ricerca', 'Start up/Sviluppo d impresa', 'Digitalizzazione'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Startup innovative ammissibili ai sensi del bando regionale',
    costMin: 50000,
    costMax: 250000,
    grantMin: 25000,
    grantMax: 150000,
    displayAmountLabel: 'Da € 25.000 a € 150.000',
    displayProjectAmountLabel: 'Da € 50.000 a € 250.000',
    displayCoverageLabel: '50% - 60%',
    coverageMinPercent: 50,
    coverageMaxPercent: 60,
    url: '/it/catalogo/regione-veneto-bando-il-consolidamento-delle-startup-innovative',
    score: 91,
  },
  {
    id: '7941',
    title: 'Regione Lombardia - Bando Musei d’impresa 2026',
    description:
      "Bando Regione Lombardia per imprese lombarde che costituiscono o riqualificano un museo d'impresa per valorizzare il patrimonio tecnico-industriale e la storia del lavoro e dell'industria regionale.",
    authorityName: 'Regione Lombardia',
    openDate: '2026-03-02T00:00:00',
    closeDate: '2026-04-24T00:00:00',
    regions: ['Lombardia'],
    sectors: ['Cultura', 'Turismo', 'Commercio', 'ICT', 'Artigianato', 'Manifattura'],
    beneficiaries: ['Impresa', 'PMI', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: [
      'Museo d impresa',
      'Valorizzazione patrimonio industriale',
      'Allestimento spazi espositivi',
      'Promozione e marketing culturale',
    ],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici ammissibili a ricevere aiuti',
    costMin: 10000,
    costMax: 80000,
    grantMin: 10000,
    grantMax: 80000,
    displayProjectAmountLabel: 'Da € 10.000 a € 80.000',
    displayCoverageLabel: '100%',
    coverageMinPercent: 100,
    coverageMaxPercent: 100,
    url: '/it/catalogo/regione-lombardia-bando-musei-dimpresa-2026',
    score: 91,
  },
  {
    id: '7452',
    title: 'Bando Nuova Impresa - Piccoli Comuni e Frazioni 2026',
    description:
      'Bando Regione Lombardia per nuove imprese o nuove unità locali che aprono attività di commercio al dettaglio alimentare e di generi di prima necessità in piccoli comuni o frazioni lombarde prive del servizio.',
    authorityName: 'Regione Lombardia',
    institutionalLink: 'https://www.bandi.regione.lombardia.it/servizi/servizio/bandi/dettaglio/attivita-produttive-commercio/sostegno-avvio-impresa/nuova-impresa-piccoli-comuni-frazioni-2026-RLO12025051423',
    openDate: '2026-01-28T00:00:00',
    closeDate: '2026-11-12T00:00:00',
    regions: ['Lombardia'],
    sectors: ['Commercio', 'Agroalimentare', 'Ristorazione'],
    beneficiaries: ['Nuova impresa', 'Impresa', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa', 'Grande Impresa'],
    purposes: ['Start up/Sviluppo d impresa', 'Commercio al dettaglio alimentare'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Commercio al dettaglio in sede fissa di prodotti alimentari e generi di prima necessita nei piccoli comuni e frazioni lombarde',
    costMin: 3000,
    costMax: 50000,
    grantMin: 2400,
    grantMax: 40000,
    displayAmountLabel: 'Da € 2.400 a € 40.000',
    displayProjectAmountLabel: 'Da € 3.000 a € 50.000',
    displayCoverageLabel: '80%',
    coverageMinPercent: 80,
    coverageMaxPercent: 80,
    url: '/it/catalogo/bando-nuova-impresa-piccoli-comuni-e-frazioni-2026',
    score: 90,
  },
  {
    id: '7669',
    title: 'Bando CONneSSi - CONtributi per lo Sviluppo di Strategie digitali per i mercati globali – 2026',
    description:
      'Bando della Camera di Commercio di Milano Monza Brianza Lodi per MPMI gia attive con strategie di digital export, ecommerce, marketplace e marketing digitale per i mercati esteri.',
    authorityName: 'Camera di Commercio Metropolitana di Milano-Monza-Brianza-Lodi',
    institutionalLink: 'https://www.milomb.camcom.it/bando-connessi-2026',
    openDate: '2026-02-05T00:00:00',
    closeDate: '2026-04-09T00:00:00',
    regions: ['Lombardia'],
    sectors: ['Commercio', 'ICT', 'Digitale', 'Turismo', 'Ristorazione', 'Artigianato', 'Altri servizi'],
    beneficiaries: ['Impresa', 'PMI', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Internazionalizzazione', 'Digitalizzazione', 'Digital export'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'MPMI con sede nelle province di Milano, Monza Brianza e Lodi, sito o ecommerce operativo e canali digitali attivi',
    costMin: 4000,
    costMax: 16667,
    grantMin: 2400,
    grantMax: 10000,
    displayAmountLabel: 'Da € 2.400 a € 10.000',
    displayProjectAmountLabel: 'Da € 4.000 a € 16.667',
    displayCoverageLabel: '60%',
    coverageMinPercent: 60,
    coverageMaxPercent: 60,
    url: '/it/catalogo/bando-connessi-contributi-lo-sviluppo-di-strategie-digitali-i-mercati-globali-2026',
    score: 91,
  },
  {
    id: '7747',
    title: 'CCIAA Cosenza - Bando sostenibilità e risparmio energetico IX Edizione',
    description:
      'Bando della Camera di Commercio di Cosenza per imprese gia attive della provincia che investono in efficientamento energetico, risparmio energetico, riciclo, riduzione emissioni e mobilita a basso impatto ambientale.',
    authorityName: 'Camera di Commercio, Industria, Artigianato e Agricoltura di Cosenza',
    institutionalLink: 'https://www.cs.camcom.gov.it/it/content/service/01-bando-sostenibilt%C3%A0-e-risparmio-energetico-ix',
    openDate: '2026-03-04T00:00:00',
    closeDate: '2026-09-30T00:00:00',
    regions: ['Calabria'],
    sectors: ['Commercio', 'Turismo', 'Artigianato', 'Agroalimentare', 'ICT', 'Manifattura', 'Servizi', 'Ristorazione'],
    beneficiaries: ['Impresa', 'PMI', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Transizione ecologica', 'Efficientamento energetico'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici ammissibili delle imprese della provincia di Cosenza',
    costMin: 2000,
    costMax: 20000,
    grantMin: 1000,
    grantMax: 12000,
    displayAmountLabel: 'Da € 1.000 a € 12.000',
    displayProjectAmountLabel: 'Da € 2.000 a € 20.000',
    displayCoverageLabel: '50% - 60%',
    coverageMinPercent: 50,
    coverageMaxPercent: 60,
    url: '/it/catalogo/cciaa-cosenza-bando-sostenibilita-e-risparmio-energetico-ix-edizione',
    score: 90,
  },
] as const;
