export const STRATEGIC_SCANNER_DOCS = [
  {
    id: 'strategic-resto-al-sud-20',
    title: 'Resto al Sud 2.0',
    description:
      "Incentivo Invitalia per under 35, disoccupati/inoccupati, working poor e nuove iniziative imprenditoriali o libero-professionali nel Mezzogiorno. Ammette turismo, commercio, servizi, digitale, artigianato, cultura, manifattura e ristorazione. Prevede voucher e contributi a fondo perduto per avvio di impresa e lavoro autonomo.",
    authorityName: 'Invitalia',
    openDate: null,
    closeDate: null,
    regions: ['Abruzzo', 'Basilicata', 'Calabria', 'Campania', 'Molise', 'Puglia', 'Sardegna', 'Sicilia'],
    sectors: ['Turismo', 'Commercio', 'Servizi', 'ICT', 'Digitale', 'Artigianato', 'Cultura', 'Ristorazione', 'Manifattura'],
    beneficiaries: ['Startup', 'Impresa', 'Aspiranti imprenditori', 'Libero professionista', 'Lavoro autonomo'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Start up/Sviluppo d impresa', 'Imprenditoria giovanile', 'Autoimpiego', 'Sostegno investimenti'],
    supportForm: ['Contributo/Fondo perduto', 'Voucher'],
    ateco: 'Tutti i settori economici ammissibili tranne agricoltura, pesca e acquacoltura',
    costMin: 40000,
    costMax: 200000,
    institutionalLink: 'https://www.invitalia.it/incentivi-e-strumenti/resto-al-sud-20',
    url: '/incentivi-e-strumenti/resto-al-sud-20',
    score: 100,
  },
  {
    id: 'strategic-smartstart-italia',
    title: 'Smart&Start Italia',
    description:
      "Incentivo Invitalia per startup innovative e nuove imprese ad alto contenuto tecnologico. Sostiene progetti di innovazione, digitale, software, ricerca, sviluppo prodotto e crescita d impresa, con condizioni rafforzate nel Centro-Sud.",
    authorityName: 'Invitalia',
    openDate: null,
    closeDate: null,
    regions: ['Italia'],
    sectors: ['ICT', 'Digitale', 'Innovazione', 'Ricerca', 'Servizi', 'Manifattura'],
    beneficiaries: ['Startup innovativa', 'Impresa', 'Nuova impresa'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Innovazione e ricerca', 'Start up/Sviluppo d impresa', 'Digitalizzazione'],
    supportForm: ['Finanziamento agevolato', 'Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici delle startup innovative',
    costMin: 100000,
    costMax: 1500000,
    institutionalLink: 'https://www.invitalia.it/cosa-facciamo/creiamo-nuove-aziende/smartstart-italia',
    url: '/cosa-facciamo/creiamo-nuove-aziende/smartstart-italia',
    score: 95,
  },
  {
    id: 'strategic-on-oltre-nuove-imprese',
    title: 'ON - Oltre Nuove imprese a tasso zero',
    description:
      "Misura Invitalia per nuove micro e piccole imprese giovanili o femminili. Favorisce avvio di impresa, investimento produttivo, turismo, servizi, commercio e manifattura con mix di finanziamento agevolato e contributo.",
    authorityName: 'Invitalia',
    openDate: null,
    closeDate: null,
    regions: ['Italia'],
    sectors: ['Turismo', 'Commercio', 'Servizi', 'Manifattura', 'Artigianato', 'Cultura'],
    beneficiaries: ['Nuova impresa', 'Impresa giovanile', 'Impresa femminile', 'Startup'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Start up/Sviluppo d impresa', 'Imprenditoria giovanile', 'Imprenditoria femminile', 'Sostegno investimenti'],
    supportForm: ['Finanziamento agevolato', 'Contributo/Fondo perduto'],
    ateco: 'Settori produttivi, turismo, commercio e servizi',
    costMin: 50000,
    costMax: 3000000,
    institutionalLink: 'https://www.invitalia.it/cosa-facciamo/creiamo-nuove-aziende/nuove-imprese-a-tasso-zero',
    url: '/cosa-facciamo/creiamo-nuove-aziende/nuove-imprese-a-tasso-zero',
    score: 92,
  },
  {
    id: 'strategic-fondo-impresa-femminile',
    title: 'Fondo impresa femminile',
    description:
      "Agevolazione Invitalia per avvio e consolidamento di imprese femminili, con contributi e finanziamenti per investimento, servizi, commercio, turismo, manifattura e innovazione.",
    authorityName: 'Invitalia',
    openDate: null,
    closeDate: null,
    regions: ['Italia'],
    sectors: ['Turismo', 'Commercio', 'Servizi', 'Manifattura', 'Artigianato', 'Innovazione'],
    beneficiaries: ['Impresa femminile', 'Nuova impresa', 'Impresa'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Imprenditoria femminile', 'Start up/Sviluppo d impresa', 'Sostegno investimenti'],
    supportForm: ['Contributo/Fondo perduto', 'Finanziamento agevolato'],
    ateco: 'Settori economici ammissibili per imprese femminili',
    costMin: 30000,
    costMax: 400000,
    institutionalLink: 'https://www.invitalia.it/cosa-facciamo/creiamo-nuove-aziende/fondo-impresa-femminile',
    url: '/cosa-facciamo/creiamo-nuove-aziende/fondo-impresa-femminile',
    score: 88,
  },
  {
    id: 'strategic-nuova-sabatini',
    title: 'Nuova Sabatini',
    description:
      "Misura nazionale per PMI gia attive che investono in macchinari, beni strumentali, digitale, software, hardware, tecnologie 4.0 e transizione digitale.",
    authorityName: 'MIMIT',
    openDate: null,
    closeDate: null,
    regions: ['Italia'],
    sectors: ['Manifattura', 'Digitale', 'ICT', 'Commercio', 'Servizi'],
    beneficiaries: ['PMI', 'Impresa', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Digitalizzazione', 'Sostegno investimenti', 'Industria 4 0'],
    supportForm: ['Finanziamento agevolato', 'Contributo'],
    ateco: 'PMI ammissibili nei settori economici previsti dalla misura',
    costMin: 20000,
    costMax: 4000000,
    institutionalLink: 'https://www.mimit.gov.it/it/incentivi/nuova-sabatini',
    url: '/it/incentivi/nuova-sabatini',
    score: 86,
  },
] as const;
