export const STRATEGIC_SCANNER_DOCS = [
  {
    id: 'strategic-autoimpiego-centro-nord',
    title: 'Autoimpiego Centro-Nord',
    description:
      "Incentivo Invitalia per giovani under 35 inattivi, inoccupati, disoccupati, disoccupati GOL e working poor che vogliono avviare una nuova attività nel Centro-Nord. Sostiene nuove iniziative d'impresa, lavoro autonomo e libera professione con voucher e contributi a fondo perduto.",
    authorityName: 'Invitalia',
    openDate: null,
    closeDate: null,
    regions: [
      'Piemonte',
      "Valle d'Aosta",
      'Liguria',
      'Lombardia',
      'Veneto',
      'Friuli-Venezia Giulia',
      'Trentino-Alto Adige',
      'Emilia-Romagna',
      'Toscana',
      'Lazio',
      'Umbria',
      'Marche',
    ],
    sectors: ['Turismo', 'Commercio', 'Servizi', 'ICT', 'Digitale', 'Artigianato', 'Cultura', 'Ristorazione', 'Manifattura'],
    beneficiaries: [
      'Startup',
      'Aspiranti imprenditori',
      'Libero professionista',
      'Lavoro autonomo',
      'Under 35',
      'Disoccupati',
      'Inoccupati',
      'Working poor',
    ],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Start up/Sviluppo d impresa', 'Imprenditoria giovanile', 'Autoimpiego', 'Sostegno investimenti'],
    supportForm: ['Contributo/Fondo perduto', 'Voucher'],
    ateco: 'Tutti i settori economici ammissibili tranne agricoltura, pesca e acquacoltura',
    costMax: 200000,
    displayAmountLabel: 'Voucher fino a € 30.000 - € 40.000',
    displayProjectAmountLabel: 'Fino a € 200.000',
    displayCoverageLabel: '60% - 100%',
    coverageMinPercent: 60,
    coverageMaxPercent: 100,
    institutionalLink: 'https://www.invitalia.it/incentivi-e-strumenti/autoimpiego-centro-nord',
    url: '/incentivi-e-strumenti/autoimpiego-centro-nord',
    score: 99,
  },
  {
    id: 'strategic-resto-al-sud-20',
    title: 'Resto al Sud 2.0',
    description:
      "Nuova misura (DL Coesione 2024) per l'avvio di attività imprenditoriali e libero-professionali. Requisiti rigorosi: età UNDER 35, disoccupati da almeno 6 mesi, inoccupati o working poor. NON confondere con la vecchia misura 'Resto al Sud' (che arrivava a 55 anni). Resto al Sud 2.0 è limitata al Mezzogiorno (Abruzzo, Basilicata, Calabria, Campania, Molise, Puglia, Sardegna, Sicilia) e aree Sisma Centro Italia. Prevede voucher fino a 50k per l'avvio e contributi a fondo perduto fino al 75% per investimenti fino a 200k.",
    authorityName: 'Invitalia',
    openDate: '2024-09-01T00:00:00', // Indicativo avvio operativo
    closeDate: '2025-12-31T00:00:00',
    regions: ['Abruzzo', 'Basilicata', 'Calabria', 'Campania', 'Molise', 'Puglia', 'Sardegna', 'Sicilia'],
    sectors: ['Turismo', 'Commercio', 'Servizi', 'ICT', 'Digitale', 'Artigianato', 'Cultura', 'Ristorazione', 'Manifattura'],
    beneficiaries: ['Aspiranti imprenditori', 'Libero professionista', 'Startup', 'Nuova impresa', 'Giovani under 35'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Start up/Sviluppo d impresa', 'Autoimpiego', 'Imprenditoria giovanile', 'Lavoro autonomo'],
    supportForm: ['Contributo/Fondo perduto', 'Voucher'],
    ateco: 'Tutti i settori tranne agricoltura primaria e pesca',
    costMin: 10000,
    costMax: 200000,
    displayAmountLabel: 'Voucher avvio (fino 50k Mezzogiorno) + Fondo perduto fino a 75%',
    displayProjectAmountLabel: 'Investimenti fino a € 200.000',
    displayCoverageLabel: '75% - 100%',
    coverageMinPercent: 75,
    coverageMaxPercent: 100,
    institutionalLink: 'https://www.invitalia.it/incentivi-e-strumenti/resto-al-sud-20',
    url: '/incentivi-e-strumenti/resto-al-sud-20',
    score: 100,
  },
  {
    id: '81',
    title: 'Smart&Start Italia - Sostegno alle startup innovative',
    description:
      "Incentivo Invitalia per startup innovative e nuove imprese ad alto contenuto tecnologico. Sostiene progetti di innovazione, digitale, software, ricerca, sviluppo prodotto e crescita d impresa, con condizioni rafforzate nel Centro-Sud.",
    authorityName: 'Invitalia',
    openDate: null,
    closeDate: null,
    regions: ['Italia'],
    sectors: ['ICT', 'Digitale', 'Innovazione', 'Ricerca', 'Servizi', 'Manifattura'],
    beneficiaries: ['Startup innovativa', 'Impresa', 'Nuova impresa'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Innovazione e ricerca', 'Start up/Sviluppo d impresa', 'Digitalizzazione'],
    supportForm: ['Finanziamento agevolato', 'Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici delle startup innovative',
    costMin: 100000,
    costMax: 1500000,
    displayProjectAmountLabel: 'Da € 100.000 a € 1.500.000',
    displayCoverageLabel: '0%',
    coverageMinPercent: 0,
    coverageMaxPercent: 0,
    url: '/it/catalogo/smartstart-italia-sostegno-alle-startup-innovative',
    score: 95,
  },
  {
    id: 'strategic-fusese',
    title: 'FUSESE - Fund for self employment and self entrepreneurship',
    description:
      "Programma europeo gestito in Italia dalla Regione Calabria e altri enti per favorire l'autoimpiego e l'avvio di nuove attivita imprenditoriali, con contributi a fondo perduto e servizi di accompagnamento per giovani, disoccupati e inoccupati nel Mezzogiorno.",
    authorityName: 'Regione Calabria',
    openDate: null,
    closeDate: null,
    regions: ['Calabria', 'Campania', 'Puglia', 'Sicilia', 'Basilicata', 'Sardegna', 'Molise', 'Abruzzo'],
    sectors: ['Turismo', 'Commercio', 'Servizi', 'ICT', 'Digitale', 'Artigianato', 'Cultura', 'Ristorazione', 'Manifattura'],
    beneficiaries: ['Startup', 'Aspiranti imprenditori', 'Disoccupati', 'Inoccupati', 'Under 35', 'Lavoro autonomo'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Start up/Sviluppo d impresa', 'Autoimpiego', 'Imprenditoria giovanile'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici ammissibili',
    costMin: 5000,
    costMax: 50000,
    displayProjectAmountLabel: 'Fino a € 50.000',
    displayCoverageLabel: '65% - 80%',
    coverageMinPercent: 65,
    coverageMaxPercent: 80,
    url: '/fusese',
    score: 94,
  },
  {
    id: '83',
    title: 'ON - Oltre Nuove imprese a tasso zero',
    description:
      "Misura Invitalia per nuove micro e piccole imprese giovanili o femminili. Favorisce avvio di impresa, investimento produttivo, turismo, servizi, commercio e manifattura con mix di finanziamento agevolato e contributo a fondo perduto.",
    authorityName: "Invitalia - Agenzia nazionale per l'attrazione degli investimenti e lo sviluppo d'impresa S.p.A.",
    openDate: null,
    closeDate: null,
    regions: ['Italia'],
    sectors: ['Turismo', 'Commercio', 'Servizi', 'Manifattura', 'Artigianato', 'Cultura'],
    beneficiaries: ['Nuova impresa', 'Impresa giovanile', 'Impresa femminile', 'Startup'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Start up/Sviluppo d impresa', 'Imprenditoria giovanile', 'Imprenditoria femminile', 'Sostegno investimenti'],
    supportForm: ['Finanziamento agevolato', 'Contributo/Fondo perduto'],
    ateco: 'Settori produttivi, turismo, commercio e servizi',
    costMin: 50000,
    costMax: 3000000,
    displayProjectAmountLabel: 'Fino a € 3.000.000',
    displayCoverageLabel: '20%',
    coverageMinPercent: 20,
    coverageMaxPercent: 20,
    grantMax: 600000,
    url: '/it/catalogo/oltre-nuove-imprese-tasso-zero',
    score: 92,
  },
  {
    id: 'strategic-fondo-impresa-femminile',
    title: 'Fondo impresa femminile',
    description:
      "Agevolazione Invitalia per avvio e consolidamento di imprese femminili, con contributi e finanziamenti per investimento, servizi, commercio, turismo, manifattura e innovazione.",
    authorityName: 'Invitalia',
    openDate: null,
    closeDate: null,
    regions: ['Italia'],
    sectors: ['Turismo', 'Commercio', 'Servizi', 'Manifattura', 'Artigianato', 'Innovazione'],
    beneficiaries: ['Impresa femminile', 'Nuova impresa', 'Impresa'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Imprenditoria femminile', 'Start up/Sviluppo d impresa', 'Sostegno investimenti'],
    supportForm: ['Contributo/Fondo perduto', 'Finanziamento agevolato'],
    ateco: 'Settori economici ammissibili per imprese femminili',
    costMin: 30000,
    costMax: 400000,
    displayProjectAmountLabel: 'Da € 30.000 a € 400.000',
    displayCoverageLabel: '0%',
    coverageMinPercent: 0,
    coverageMaxPercent: 0,
    institutionalLink: 'https://www.invitalia.it/cosa-facciamo/creiamo-nuove-aziende/fondo-impresa-femminile',
    url: '/cosa-facciamo/creiamo-nuove-aziende/fondo-impresa-femminile',
    score: 88,
  },
  {
    id: '52',
    title: 'Beni Strumentali - Nuova Sabatini',
    description:
      "Misura nazionale per PMI gia attive che investono in macchinari, beni strumentali, digitale, software, hardware, tecnologie 4.0 e transizione digitale.",
    authorityName: 'Ministero delle Imprese e del Made in Italy',
    openDate: null,
    closeDate: null,
    regions: ['Italia'],
    sectors: ['Manifattura', 'Digitale', 'ICT', 'Commercio', 'Servizi'],
    beneficiaries: ['PMI', 'Impresa', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Digitalizzazione', 'Sostegno investimenti', 'Industria 4 0'],
    supportForm: ['Finanziamento agevolato', 'Contributo'],
    ateco: 'PMI ammissibili nei settori economici previsti dalla misura',
    costMin: 20000,
    costMax: 4000000,
    grantMin: 550,
    grantMax: 143000,
    displayAmountLabel: 'Contributo calcolato su finanziamenti da € 20.000 a € 4.000.000',
    displayProjectAmountLabel: 'Da € 20.000 a € 4.000.000',
    displayCoverageLabel: '0%',
    coverageMinPercent: 0,
    coverageMaxPercent: 0,
    url: '/it/incentivi/nuova-sabatini',
    score: 86,
  },
  {
    id: '2689',
    title: 'Polo di Innovazione Digitale PIDNEXT - servizi di first e post assessment',
    description:
      "Misura del sistema camerale per micro, piccole e medie imprese gia attive e iscritte al registro delle imprese che vogliono valutare la maturita digitale e ricevere servizi di first assessment e orientamento verso la trasformazione digitale.",
    authorityName: 'Ministero delle Imprese e del Made in Italy',
    openDate: '2023-03-10T00:00:00',
    closeDate: '2026-04-30T00:00:00',
    regions: [
      'Piemonte',
      'Lombardia',
      "Valle d'Aosta",
      'Liguria',
      'Abruzzo',
      'Molise',
      'Basilicata',
      'Calabria',
      'Campania',
      'Puglia',
      'Sicilia',
      'Trentino-Alto Adige',
      'Veneto',
      'Sardegna',
      'Toscana',
      'Friuli-Venezia Giulia',
      'Emilia-Romagna',
      'Umbria',
      'Marche',
      'Lazio',
    ],
    sectors: [
      'Agroalimentare',
      'Alberghiero',
      'Altri servizi',
      'Artigianato',
      'Commercio',
      'Cultura',
      'Edilizia',
      'ICT',
      'Manifattura',
      'Ristorazione',
      'Turismo',
    ],
    beneficiaries: ['Impresa', 'PMI', 'Azienda gia attiva', 'Impresa iscritta al registro imprese'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Digitalizzazione', 'Innovazione e ricerca', 'Start up/Sviluppo d impresa'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici ammissibili a ricevere aiuti',
    costMax: 2883,
    grantMax: 2883,
    displayProjectAmountLabel: 'Fino a € 2.883',
    displayCoverageLabel: '100%',
    coverageMinPercent: 100,
    coverageMaxPercent: 100,
    url: '/it/catalogo/polo-di-innovazione-digitale-pidnext-servizi-di-first-e-post-assessment',
    score: 90,
  },
  {
    id: '3800',
    title: 'PR Marche FESR 2021/2027 – Intervento 1.3.4.1 - Partecipazione delle imprese alla fiera SMAU Milano 2026',
    description:
      "Bando Regione Marche per startup e PMI innovative marchigiane gia costituite che partecipano a SMAU Milano 2026 con spazi espositivi e attivita di promozione per l'internazionalizzazione.",
    authorityName: 'Regione Marche',
    openDate: '2026-02-20T00:00:00',
    closeDate: '2026-04-16T00:00:00',
    regions: ['Marche'],
    sectors: ['Altri servizi', 'ICT', 'Digitale', 'Innovazione'],
    beneficiaries: ['Startup innovativa', 'PMI innovativa', 'Impresa', 'Impresa gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Internazionalizzazione', 'Innovazione e ricerca'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici ammissibili a ricevere aiuti',
    costMax: 5000,
    grantMax: 5000,
    displayProjectAmountLabel: 'Fino a € 5.000',
    displayCoverageLabel: '100%',
    coverageMinPercent: 100,
    coverageMaxPercent: 100,
    url: '/it/catalogo/pr-marche-fesr-20212027-intervento-1341-partecipazione-delle-imprese-alla-fiera-smau',
    score: 89,
  },
  {
    id: '7755',
    title: 'CCIAA Cosenza - Bando Voucher digitali I4.0 Anno 2026 XII Edizione – PID avanzato',
    description:
      "Bando della Camera di Commercio di Cosenza per micro, piccole e medie imprese gia attive della provincia che investono in digitalizzazione, ecommerce, CRM, cybersecurity, software e tecnologie 4.0.",
    authorityName: 'Camera di Commercio, Industria, Artigianato e Agricoltura di Cosenza',
    openDate: '2026-03-04T00:00:00',
    closeDate: '2026-09-30T00:00:00',
    regions: ['Calabria'],
    sectors: [
      'Altri servizi',
      'Artigianato',
      'Commercio',
      'ICT',
      'Manifattura',
      'Turismo',
      'Ristorazione',
      'Agroalimentare',
    ],
    beneficiaries: ['Impresa', 'PMI', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Digitalizzazione', 'Innovazione e ricerca'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici ammissibili a ricevere aiuti',
    costMin: 4000,
    costMax: 20000,
    grantMin: 2000,
    grantMax: 10000,
    displayAmountLabel: 'Da € 2.000 a € 10.000',
    displayProjectAmountLabel: 'Da € 4.000 a € 20.000',
    displayCoverageLabel: '50% - 70%',
    coverageMinPercent: 50,
    coverageMaxPercent: 70,
    url: '/it/catalogo/cciaa-cosenza-bando-voucher-digitali-i40-anno-2026-xii-edizione-pid-avanzato',
    score: 90,
  },
  {
    id: '7786',
    title: 'CCIAA Bologna - Contributi per la partecipazione a fiere internazionali in Italia - Anno 2026',
    description:
      "Bando della Camera di Commercio di Bologna per micro, piccole e medie imprese gia attive della citta metropolitana che partecipano a fiere internazionali certificate in Italia.",
    authorityName: 'Camera di Commercio, Industria, Artigianato e Agricoltura di Bologna',
    openDate: '2026-01-01T00:00:00',
    closeDate: '2026-12-31T00:00:00',
    regions: ['Emilia-Romagna'],
    sectors: ['Commercio', 'Manifattura', 'Servizi', 'Turismo', 'Artigianato', 'ICT'],
    beneficiaries: ['Impresa', 'PMI', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Internazionalizzazione'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici ammissibili a ricevere aiuti',
    costMin: 3000,
    costMax: 8000,
    grantMin: 1500,
    grantMax: 4000,
    displayAmountLabel: 'Da € 1.500 a € 4.000',
    displayProjectAmountLabel: 'Da € 3.000 a € 8.000',
    displayCoverageLabel: '50%',
    coverageMinPercent: 50,
    coverageMaxPercent: 50,
    url: '/it/catalogo/cciaa-bologna-contributi-la-partecipazione-fiere-internazionali-italia-anno-2026',
    score: 88,
  },
  {
    id: '7875',
    title: 'Regione Veneto - Bando per il consolidamento delle startup innovative',
    description:
      'Bando Regione Veneto per startup innovative gia costituite che vogliono consolidarsi con progetti di ricerca, innovazione, assunzione di personale qualificato e collaborazione con organismi di ricerca.',
    authorityName: 'Agenzia veneta per i pagamenti in agricoltura - AVEPA',
    openDate: '2026-02-10T00:00:00',
    closeDate: null,
    regions: ['Veneto'],
    sectors: ['ICT', 'Digitale', 'Innovazione', 'Servizi', 'Manifattura', 'Ricerca'],
    beneficiaries: ['Startup innovativa', 'Impresa', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Innovazione e ricerca', 'Start up/Sviluppo d impresa', 'Digitalizzazione'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Startup innovative ammissibili ai sensi del bando regionale',
    costMin: 50000,
    costMax: 250000,
    grantMin: 25000,
    grantMax: 150000,
    displayAmountLabel: 'Da € 25.000 a € 150.000',
    displayProjectAmountLabel: 'Da € 50.000 a € 250.000',
    displayCoverageLabel: '50% - 60%',
    coverageMinPercent: 50,
    coverageMaxPercent: 60,
    url: '/it/catalogo/regione-veneto-bando-il-consolidamento-delle-startup-innovative',
    score: 91,
  },
  {
    id: '7941',
    title: 'Regione Lombardia - Bando Musei d’impresa 2026',
    description:
      "Bando Regione Lombardia per imprese lombarde che costituiscono o riqualificano un museo d'impresa per valorizzare il patrimonio tecnico-industriale e la storia del lavoro e dell'industria regionale.",
    authorityName: 'Regione Lombardia',
    openDate: '2026-03-02T00:00:00',
    closeDate: '2026-04-24T00:00:00',
    regions: ['Lombardia'],
    sectors: ['Cultura', 'Turismo', 'Commercio', 'ICT', 'Artigianato', 'Manifattura'],
    beneficiaries: ['Impresa', 'PMI', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: [
      'Museo d impresa',
      'Valorizzazione patrimonio industriale',
      'Allestimento spazi espositivi',
      'Promozione e marketing culturale',
    ],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici ammissibili a ricevere aiuti',
    costMin: 10000,
    costMax: 80000,
    grantMin: 10000,
    grantMax: 80000,
    displayProjectAmountLabel: 'Da € 10.000 a € 80.000',
    displayCoverageLabel: '100%',
    coverageMinPercent: 100,
    coverageMaxPercent: 100,
    url: '/it/catalogo/regione-lombardia-bando-musei-dimpresa-2026',
    score: 91,
  },
  {
    id: '7452',
    title: 'Bando Nuova Impresa - Piccoli Comuni e Frazioni 2026',
    description:
      'Bando Regione Lombardia per nuove imprese o nuove unità locali che aprono attività di commercio al dettaglio alimentare e di generi di prima necessità in piccoli comuni o frazioni lombarde prive del servizio.',
    authorityName: 'Regione Lombardia',
    institutionalLink: 'https://www.bandi.regione.lombardia.it/servizi/servizio/bandi/dettaglio/attivita-produttive-commercio/sostegno-avvio-impresa/nuova-impresa-piccoli-comuni-frazioni-2026-RLO12025051423',
    openDate: '2026-01-28T00:00:00',
    closeDate: '2026-11-12T00:00:00',
    regions: ['Lombardia'],
    sectors: ['Commercio', 'Agroalimentare', 'Ristorazione'],
    beneficiaries: ['Nuova impresa', 'Impresa', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa', 'Grande Impresa'],
    purposes: ['Start up/Sviluppo d impresa', 'Commercio al dettaglio alimentare'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Commercio al dettaglio in sede fissa di prodotti alimentari e generi di prima necessita nei piccoli comuni e frazioni lombarde',
    costMin: 3000,
    costMax: 50000,
    grantMin: 2400,
    grantMax: 40000,
    displayAmountLabel: 'Da € 2.400 a € 40.000',
    displayProjectAmountLabel: 'Da € 3.000 a € 50.000',
    displayCoverageLabel: '80%',
    coverageMinPercent: 80,
    coverageMaxPercent: 80,
    url: '/it/catalogo/bando-nuova-impresa-piccoli-comuni-e-frazioni-2026',
    score: 90,
  },
  {
    id: '7669',
    title: 'Bando CONneSSi - CONtributi per lo Sviluppo di Strategie digitali per i mercati globali – 2026',
    description:
      'Bando della Camera di Commercio di Milano Monza Brianza Lodi per MPMI gia attive con strategie di digital export, ecommerce, marketplace e marketing digitale per i mercati esteri.',
    authorityName: 'Camera di Commercio Metropolitana di Milano-Monza-Brianza-Lodi',
    institutionalLink: 'https://www.milomb.camcom.it/bando-connessi-2026',
    openDate: '2026-02-05T00:00:00',
    closeDate: '2026-04-09T00:00:00',
    regions: ['Lombardia'],
    sectors: ['Commercio', 'ICT', 'Digitale', 'Turismo', 'Ristorazione', 'Artigianato', 'Altri servizi'],
    beneficiaries: ['Impresa', 'PMI', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Internazionalizzazione', 'Digitalizzazione', 'Digital export'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'MPMI con sede nelle province di Milano, Monza Brianza e Lodi, sito o ecommerce operativo e canali digitali attivi',
    costMin: 4000,
    costMax: 16667,
    grantMin: 2400,
    grantMax: 10000,
    displayAmountLabel: 'Da € 2.400 a € 10.000',
    displayProjectAmountLabel: 'Da € 4.000 a € 16.667',
    displayCoverageLabel: '60%',
    coverageMinPercent: 60,
    coverageMaxPercent: 60,
    url: '/it/catalogo/bando-connessi-contributi-lo-sviluppo-di-strategie-digitali-i-mercati-globali-2026',
    score: 91,
  },
  {
    id: '7747',
    title: 'CCIAA Cosenza - Bando sostenibilità e risparmio energetico IX Edizione',
    description:
      'Bando della Camera di Commercio di Cosenza per imprese gia attive della provincia che investono in efficientamento energetico, risparmio energetico, riciclo, riduzione emissioni e mobilita a basso impatto ambientale.',
    authorityName: 'Camera di Commercio, Industria, Artigianato e Agricoltura di Cosenza',
    institutionalLink: 'https://www.cs.camcom.gov.it/it/content/service/01-bando-sostenibilt%C3%A0-e-risparmio-energetico-ix',
    openDate: '2026-03-04T00:00:00',
    closeDate: '2026-09-30T00:00:00',
    regions: ['Calabria'],
    sectors: ['Commercio', 'Turismo', 'Artigianato', 'Agroalimentare', 'ICT', 'Manifattura', 'Servizi', 'Ristorazione'],
    beneficiaries: ['Impresa', 'PMI', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Transizione ecologica', 'Efficientamento energetico'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Tutti i settori economici ammissibili delle imprese della provincia di Cosenza',
    costMin: 2000,
    costMax: 20000,
    grantMin: 1000,
    grantMax: 12000,
    displayAmountLabel: 'Da € 1.000 a € 12.000',
    displayProjectAmountLabel: 'Da € 2.000 a € 20.000',
    displayCoverageLabel: '50% - 60%',
    coverageMinPercent: 50,
    coverageMaxPercent: 60,
    url: '/it/catalogo/cciaa-cosenza-bando-sostenibilita-e-risparmio-energetico-ix-edizione',
    score: 90,
  },
  {
    id: 'strategic-transizione-50',
    title: 'Transizione 5.0 - Credito d\'Imposta',
    description: "Incentivo nazionale per imprese che effettuano nuovi investimenti in strutture produttive ubicate nel territorio dello Stato, nell'ambito di progetti di innovazione che conseguono una riduzione dei consumi energetici.",
    authorityName: 'MIMIT - Ministero delle Imprese e del Made in Italy',
    institutionalLink: 'https://www.mimit.gov.it/it/incentivi/transizione-5-0',
    openDate: '2024-08-07T00:00:00',
    closeDate: '2025-12-31T00:00:00',
    regions: [], // Nazionale
    sectors: ['Manifattura', 'ICT', 'Servizi', 'Turismo', 'Agroalimentare', 'Trasporti'],
    beneficiaries: ['Impresa', 'PMI', 'Grande Impresa'],
    dimensions: ['Piccola Impresa', 'Media Impresa', 'Grande Impresa'],
    purposes: ['Transizione ecologica', 'Efficientamento energetico', 'Digitalizzazione', 'Innovazione'],
    supportForm: ['Credito d\'Imposta'],
    ateco: 'Tutti i settori tranne attività escluse (es. combustibili fossili, ETS)',
    costMax: 50000000,
    displayAmountLabel: 'Credito d\'imposta fino al 45%',
    displayProjectAmountLabel: 'Fino a € 50.000.000',
    displayCoverageLabel: '35% - 45%',
    coverageMinPercent: 35,
    coverageMaxPercent: 45,
    url: '/incentivi/transizione-50',
    score: 98,
  },
  {
    id: 'strategic-zes-unica-sud',
    title: 'ZES Unica Mezzogiorno - Credito d\'Imposta Investimenti',
    description: 'Credito d\'imposta per le imprese che effettuano l\'acquisizione di beni strumentali destinati a strutture produttive ubicate nelle zone assistite delle regioni Basilicata, Calabria, Campania, Molise, Puglia, Sardegna, Sicilia e Abruzzo.',
    authorityName: 'Agenzia delle Entrate / Presidenza del Consiglio',
    institutionalLink: 'https://www.agenziaentrate.gov.it/portale/web/guest/credito-d-imposta-zes-unica',
    openDate: '2024-06-12T00:00:00',
    closeDate: '2024-11-15T00:00:00',
    regions: ['Calabria', 'Campania', 'Puglia', 'Sicilia', 'Basilicata', 'Sardegna', 'Molise', 'Abruzzo'],
    sectors: ['Manifattura', 'Agroalimentare', 'Turismo', 'Commercio', 'Servizi'],
    beneficiaries: ['Azienda gia attiva', 'Impresa', 'PMI'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa', 'Grande Impresa'],
    purposes: ['Sostegno investimenti', 'Beni strumentali', 'Sviluppo Mezzogiorno'],
    supportForm: ['Credito d\'Imposta'],
    ateco: 'Tutti i settori tranne trasporti, energia, siderurgia, creditizio',
    costMin: 200000,
    displayAmountLabel: 'Credito d\'imposta fino al 60%',
    displayProjectAmountLabel: 'Minimo € 200.000',
    displayCoverageLabel: 'Variable per regione e dimensione',
    coverageMinPercent: 15,
    coverageMaxPercent: 60,
    url: '/incentivi/zes-unica-sud',
    score: 97,
  },
  {
    id: 'strategic-pmi-campania-startup',
    title: 'Campania Startup 2024',
    description: 'Bando della Regione Campania per il sostegno alla creazione e al consolidamento di startup innovative ad alta intensità di conoscenza, per aumentare la competitività del sistema produttivo regionale.',
    authorityName: 'Regione Campania',
    institutionalLink: 'https://regione.campania.it/regione/it/tematiche/startup-campania',
    openDate: '2024-05-15T00:00:00',
    closeDate: '2025-03-30T00:00:00',
    regions: ['Campania'],
    sectors: ['ICT', 'Digitale', 'Ricerca e Sviluppo', 'Biotecnologie', 'Cultura', 'Turismo'],
    beneficiaries: ['Startup', 'Nuova impresa', 'Aspiranti imprenditori'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Start up/Sviluppo d impresa', 'Digitalizzazione', 'Innovazione'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Settori ad alta tecnologia e conoscenza',
    costMin: 50000,
    costMax: 500000,
    grantMax: 350000,
    displayAmountLabel: 'Contributo fino a € 350.000',
    displayProjectAmountLabel: 'Minimo € 50.000',
    displayCoverageLabel: '70% - 80%',
    coverageMinPercent: 70,
    coverageMaxPercent: 80,
    url: '/incentivi/campania-startup-2024',
    score: 95,
  },
  {
    id: 'strategic-puglia-tecnonidi',
    title: 'Tecnonidi Puglia',
    description: 'Bando della Regione Puglia per il sostegno alle startup tecnologiche e alle piccole imprese innovative che intendono avviare o sviluppare piani di investimento a contenuto tecnologico.',
    authorityName: 'Regione Puglia - Puglia Sviluppo',
    institutionalLink: 'https://pugliasviluppo.regione.puglia.it/it/tecnonidi',
    openDate: null, // Sempre aperto
    closeDate: null,
    regions: ['Puglia'],
    sectors: ['ICT', 'Manifattura', 'Salute', 'Ambiente', 'Energia'],
    beneficiaries: ['Startup', 'PMI', 'Azienda gia attiva'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Innovazione tecnologica', 'Ricerca e Sviluppo', 'Start up/Sviluppo d impresa'],
    supportForm: ['Contributo/Fondo perduto', 'Finanziamento agevolato'],
    ateco: 'Settori tecnologici e manifatturieri innovativi',
    costMin: 25000,
    costMax: 350000,
    displayAmountLabel: 'Fino a € 280.000 (Misto)',
    displayProjectAmountLabel: 'Da € 25.000 a € 350.000',
    displayCoverageLabel: '80%',
    coverageMinPercent: 80,
    coverageMaxPercent: 80,
    url: '/incentivi/puglia-tecnonidi',
    score: 94,
  },
  {
    id: 'strategic-sicilia-fare-impresa',
    title: 'Fare Impresa in Sicilia - Bonus Occupazione',
    description: 'Incentivo della Regione Siciliana per favorire l\'autoimprenditorialità e il ricambio generazionale attraverso contributi per l\'avvio di nuove imprese da parte di giovani e donne.',
    authorityName: 'Regione Siciliana',
    institutionalLink: 'https://pti.regione.sicilia.it/',
    openDate: '2024-03-01T00:00:00',
    closeDate: '2025-12-31T00:00:00',
    regions: ['Sicilia'],
    sectors: ['Commercio', 'Artigianato', 'Servizi', 'Turismo', 'Cultura'],
    beneficiaries: ['Aspiranti imprenditori', 'Nuova impresa', 'Giovani', 'Donne'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Autoimpiego', 'Imprenditoria giovanile', 'Imprenditoria femminile'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: 'Ampio spettro di settori economici',
    costMin: 10000,
    costMax: 100000,
    displayAmountLabel: 'Contributo fino a € 90.000',
    displayProjectAmountLabel: 'Fino a € 100.000',
    displayCoverageLabel: '90%',
    coverageMinPercent: 90,
    coverageMaxPercent: 90,
    url: '/incentivi/sicilia-fare-impresa',
    score: 93,
  },
  {
    id: 'strategic-lazio-startup',
    title: 'Startup Lazio - Voucher Internazionalizzazione',
    description: 'Bando della Regione Lazio per sostenere l\'accesso ai mercati esteri delle startup innovative del territorio attraverso voucher per servizi di consulenza e partecipazione a fiere.',
    authorityName: 'Regione Lazio - Lazio Innova',
    institutionalLink: 'https://www.lazioinnova.it/',
    openDate: '2024-06-01T00:00:00',
    closeDate: '2024-12-31T00:00:00',
    regions: ['Lazio'],
    sectors: ['Commercio', 'ICT', 'Cultura', 'Turismo', 'Manifattura'],
    beneficiaries: ['Startup'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Internazionalizzazione', 'Export', 'Sviluppo mercati'],
    supportForm: ['Voucher', 'Contributo/Fondo perduto'],
    ateco: 'Startup innovative iscritte al registro speciale',
    costMin: 5000,
    costMax: 50000,
    displayAmountLabel: 'Voucher fino a € 25.000',
    displayProjectAmountLabel: 'Da € 5.000 a € 50.000',
    displayCoverageLabel: '50%',
    coverageMinPercent: 50,
    coverageMaxPercent: 50,
    url: '/incentivi/lazio-startup-internazionalizzazione',
    score: 92,
  },
  {
    id: 'strategic-calabria-turismo-2024',
    title: 'Calabria Straordinaria - Bando Ricettività',
    description: 'Incentivo della Regione Calabria per il miglioramento dell\'offerta turistica e ricettiva attraverso la riqualificazione di strutture esistenti e lo sviluppo di nuovi servizi digitali.',
    authorityName: 'Regione Calabria',
    institutionalLink: 'https://calabriaeuropa.regione.calabria.it/',
    openDate: '2024-04-10T00:00:00',
    closeDate: '2024-10-30T00:00:00',
    regions: ['Calabria'],
    sectors: ['Turismo', 'Ristorazione', 'Cultura'],
    beneficiaries: ['Azienda gia attiva', 'Impresa', 'PMI'],
    dimensions: ['Piccola Impresa', 'Media Impresa'],
    purposes: ['Riqualificazione turistica', 'Digitalizzazione', 'Sostenibilità'],
    supportForm: ['Contributo/Fondo perduto'],
    ateco: '55.10, 55.20, 55.30 (Strutture ricettive)',
    costMin: 50000,
    costMax: 1000000,
    displayAmountLabel: 'Fondo perduto fino al 70%',
    displayProjectAmountLabel: 'Fino a € 1.000.000',
    displayCoverageLabel: '50% - 70%',
    coverageMinPercent: 50,
    coverageMaxPercent: 70,
    url: '/incentivi/calabria-turismo-2024',
    score: 91,
  },
  {
    id: 'strategic-pmi-digitalizzazione-2024',
    title: 'Bonus Digitalizzazione PMI Nazionale',
    description: 'Contributo a fondo perduto sotto forma di voucher per l\'acquisto di software, hardware e servizi specialistici finalizzati alla digitalizzazione dei processi aziendali e all\'ammodernamento tecnologico.',
    authorityName: 'MIMIT - Ministero delle Imprese e del Made in Italy',
    institutionalLink: 'https://www.mimit.gov.it/',
    openDate: null, // Previsto a breve
    closeDate: null,
    regions: [], // Nazionale
    sectors: ['Commercio', 'Servizi', 'Artigianato', 'Manifattura', 'Turismo'],
    beneficiaries: ['PMI', 'Micro Impresa'],
    dimensions: ['Micro Impresa', 'Piccola Impresa'],
    purposes: ['Digitalizzazione', 'E-commerce', 'Hardware/Software'],
    supportForm: ['Voucher', 'Contributo/Fondo perduto'],
    ateco: 'Quasi tutti i settori ammissibili',
    costMin: 2000,
    costMax: 15000,
    displayAmountLabel: 'Voucher fino a € 10.000',
    displayProjectAmountLabel: 'Fino a € 15.000',
    displayCoverageLabel: '50% - 100%',
    coverageMinPercent: 50,
    coverageMaxPercent: 100,
    url: '/incentivi/pmi-digitalizzazione-2024',
    score: 96,
  },
  {
    id: 'strategic-fondo-impresa-donna',
    title: 'Fondo Impresa Donna',
    description: 'Incentivo nazionale volto a sostenere la nascita e lo sviluppo di imprese a prevalente partecipazione femminile attraverso contributi a fondo perduto e finanziamenti agevolati.',
    authorityName: 'MIMIT - Invitalia',
    institutionalLink: 'https://www.invitalia.it/cosa-facciamo/creiamo-nuove-aziende/fondo-impresa-donna',
    openDate: null, // Sportelli periodici
    closeDate: null,
    regions: [], // Nazionale
    sectors: ['Manifattura', 'Servizi', 'Commercio', 'Turismo', 'ICT'],
    beneficiaries: ['Donne', 'Startup', 'PMI', 'Nuova impresa'],
    dimensions: ['Micro Impresa', 'Piccola Impresa', 'Media Impresa'],
    purposes: ['Imprenditoria femminile', 'Start up/Sviluppo d impresa', 'Beni strumentali'],
    supportForm: ['Contributo/Fondo perduto', 'Finanziamento agevolato'],
    ateco: 'Ampio spettro di settori economici ammissibili',
    costMax: 400000,
    displayAmountLabel: 'Fino a € 320.000 (Misto)',
    displayProjectAmountLabel: 'Fino a € 400.000',
    displayCoverageLabel: '50% - 80%',
    coverageMinPercent: 50,
    coverageMaxPercent: 80,
    url: '/incentivi/fondo-impresa-donna',
    score: 95,
  }
] as const;
